#define run_paper_mksky run_prefix_backend_mksky
#define run_paper_ablation_a run_prefix_backend_ablation_a
#define run_paper_ablation_b run_prefix_backend_ablation_b
#define run_paper_ablation_c run_prefix_backend_ablation_c
#define run_sum_order_mksky run_prefix_backend_sum_order
#define run_grid_mkd_mksky run_prefix_backend_grid_mkd
#define run_projection_bound_mksky run_prefix_backend_projection_bound
#define run_projection_3d_mksky run_prefix_backend_projection_3d
#define run_projection_scan_mksky run_prefix_backend_projection_scan
#define run_projection_cycle_mksky run_prefix_backend_projection_cycle
#define run_projection_qcycle_mksky run_prefix_backend_projection_qcycle

#include "mksky_prefix_backend_impl.cuh"
